#include <stdio.h>
int main()
{
    FILE * file = fopen("vm_c$.c", "w");
    if (file == NULL) { printf("\ngen_c$.c: №1"); return -1; }
    fprintf(file,
        "// Виртуальная машина C$ сгенерирована!\n"
        "#include <stdio.h>\n"
        "#include <locale.h>\n"
        "#include <stdlib.h> // для malloc/free\n"
        "int main(int argc, char * argv[])\n"
        "{\n"
        "    setlocale(0, \"\");\n"
        "    FILE * file = fopen(\"_.cdlr\", \"rb\");\n"
        "    if (file == NULL) { printf(\"\\n_.cdlr: №1\"); return -1; }\n"
        "    fseek(file, 0, SEEK_END);\n"
        "    long file_size = ftell(file);\n"
        "    printf(\"\\nfile_size = %%ld\", file_size);\n"
        "    char * opcode = malloc(file_size);\n"
        "    fseek(file, 0, SEEK_SET);\n"
        "    size_t number_of_characters_read = fread(opcode, sizeof (char), sizeof (opcode)-1, file);\n"
        "    printf(\"\\nnumber_of_characters_read = %%llu\", number_of_characters_read);\n"
        "    free(opcode);\n"
        "\n"
        "    unsigned char instruction_pointer = 0;\n"
        "    unsigned char memory[0xFF] = {0};\n"
        "\n"
        "    void * dispatcher[0xFF+1] = {\n"
        "       [0] = &&_op_invalid,\n"
        "       [1] = &&_op_jump,\n"
        "       [2] = &&_op_move,\n"
        "       [3] = &&_op_inc, [4] = &&_op_dec,\n"
        "       [5] = &&_op_add, [6] = &&_op_sub, [7] = &&_op_mul, [8] = &&_op_div,\n"
        "       [9 ... 0xFF] = &&_op_invalid\n"
        "    };\n"
        "    goto * dispatcher[opcode[instruction_pointer]];\n"
        "\n"
        "_op_jump: printf(\"\\nop_jump\");\n"
        "    goto * dispatcher[opcode[++instruction_pointer]];\n"
        "\n"
        "_op_move: printf(\"\\nop_move\"); // move [1], 0 / move *1, 0\n"
        "    memory[opcode[instruction_pointer-1]] = opcode[instruction_pointer+=2];\n"
        "    goto * dispatcher[opcode[++instruction_pointer]];\n"
        "\n"
        "_op_inc: printf(\"\\nop_inc\"); // inc [1] / inc *1\n"
        "    ++memory[opcode[++instruction_pointer]];\n"
        "    goto * dispatcher[opcode[++instruction_pointer]];\n"
        "\n"
        "_op_dec: printf(\"\\nop_dec\"); // dec [1] / dec *1\n"
        "    --memory[opcode[++instruction_pointer]];\n"
        "    goto * dispatcher[opcode[++instruction_pointer]];\n"
        "\n"
        "_op_add: printf(\"\\nop_add\"); // add [1], 1 / add *1, 1\n"
        "    memory[opcode[instruction_pointer-1]] += opcode[instruction_pointer+=2];\n"
        "    goto * dispatcher[opcode[++instruction_pointer]];\n"
        "\n"
        "_op_sub: printf(\"\\nop_sub\"); // sub [1], 1 / sub *1, 1\n"
        "    memory[opcode[instruction_pointer-1]] -= opcode[instruction_pointer+=2];\n"
        "    goto * dispatcher[opcode[++instruction_pointer]];\n"
        "\n"
        "_op_mul: printf(\"\\op_mul\"); // mul [1], 1 / mul *1, 1\n"
        "    memory[opcode[instruction_pointer-1]] *= opcode[instruction_pointer+=2];\n"
        "    goto * dispatcher[opcode[++instruction_pointer]];\n"
        "\n"
        "_op_div: printf(\"\\op_div\"); // div [1], 1 / div *1, 1\n"
        "    memory[opcode[instruction_pointer-1]] /= opcode[instruction_pointer+=2];\n"
        "    goto * dispatcher[opcode[++instruction_pointer]];\n"
        "\n"
        "_op_invalid: printf(\"\\nop_invalid\");\n"
        "\n"
    );
    fprintf(file,
        "    putchar('\\n');\n"
        "    return 0;\n"
        "}"
    );
    fclose(file);
    return 0;
}