#include <stdio.h>
int main()
{
    FILE * file = fopen("vm_c$.c", "w");
    if (file == NULL) { printf("\ngen_c$.c: №1"); return -1; }
    fprintf(file,
        "// Виртуальная машина C$ сгенерирована!\n"
        "#include <stdio.h>\n"
        "#include <locale.h>\n"
        "#include <stdlib.h> // для malloc/free\n"
        "int main(int argc, char * argv[])\n"
        "{\n"
        "    setlocale(0, \"\");\n"
        "    FILE * file = fopen(\"_.cdlr\", \"rb\");\n"
        "    if (file == NULL) { printf(\"\\n_.cdlr: №1\"); return -1; }\n"
        "    fseek(file, 0, SEEK_END);\n"
        "    long file_size = ftell(file);\n"
        "    printf(\"\\nfile_size = %%ld\", file_size);\n"
        "    char * opcode = malloc(file_size);\n"
        "    fseek(file, 0, SEEK_SET);\n"
        "    size_t number_of_characters_read = fread(opcode, sizeof (char), sizeof (opcode)-1, file);\n"
        "    printf(\"\\nnumber_of_characters_read = %%llu\", number_of_characters_read);\n"
        "    free(opcode);\n"
        "\n"
        "    unsigned char instruction_pointer = 0;\n"
        "    unsigned char memory[0xFF] = {0};\n"
        "\n"
        "    void * dispatcher[0xFF+1] = {\n"
    );
    unsigned char enumeration = 0;
    fprintf(file,
        "       [%d] = &&_op_invalid,\n"
        "       [%d] = &&jump,\n"
        "       [%d] = &&_op_move,\n"
        "       [%d] = &&_op_inc, [%d] = &&_op_dec,\n"
        "       [%d] = &&_op_add, [%d] = &&_op_sub, [%d] = &&_op_mul, [%d] = &&_op_div,\n"
        "       [%d] = &&compare,\n"
        "       [%d] = &&jump_if_not_zero,\n"
        "       [%d] = &&call, [%d] = &&push, [%d] = &&pop, [%d] = &&ret,\n"
        "       [15 ... 0xFF] = &&_op_invalid\n"
        ,
        enumeration,
        enumeration+1,
        enumeration+2,
        enumeration+3, enumeration+4,
        enumeration+5, enumeration+6, enumeration+7, enumeration+8,
        enumeration+9,
        enumeration+10,
        enumeration+11, enumeration+12, enumeration+13, enumeration+14
    );
    fprintf(file,
        "    };\n"
        "    goto * dispatcher[opcode[instruction_pointer]];\n"
        "\n"
        "/*/ START_OF_BLOCK /*/\n"
        "jump: printf(\"\\nop_jump\");\n"
        "    goto * dispatcher[opcode[++instruction_pointer]];\n"
        "\n"
        "_op_move: printf(\"\\nop_move\"); // move [1], 0 / move *1, 0\n"
        "    memory[opcode[instruction_pointer-1]] = opcode[instruction_pointer+=2];\n"
        "    goto * dispatcher[opcode[++instruction_pointer]];\n"
        "\n"
        "_op_inc: printf(\"\\nop_inc\"); // inc [1] / inc *1\n"
        "    ++memory[opcode[++instruction_pointer]];\n"
        "    goto * dispatcher[opcode[++instruction_pointer]];\n"
        "\n"
        "_op_dec: printf(\"\\nop_dec\"); // dec [1] / dec *1\n"
        "    --memory[opcode[++instruction_pointer]];\n"
        "    goto * dispatcher[opcode[++instruction_pointer]];\n"
        "\n"
        "_op_add: printf(\"\\nop_add\"); // add [1], 1 / add *1, 1\n"
        "    memory[opcode[instruction_pointer-1]] += opcode[instruction_pointer+=2];\n"
        "    goto * dispatcher[opcode[++instruction_pointer]];\n"
        "\n"
        "_op_sub: printf(\"\\nop_sub\"); // sub [1], 1 / sub *1, 1\n"
        "    memory[opcode[instruction_pointer-1]] -= opcode[instruction_pointer+=2];\n"
        "    goto * dispatcher[opcode[++instruction_pointer]];\n"
        "\n"
        "_op_mul: printf(\"\\nop_mul\"); // mul [1], 1 / mul *1, 1\n"
        "    memory[opcode[instruction_pointer-1]] *= opcode[instruction_pointer+=2];\n"
        "    goto * dispatcher[opcode[++instruction_pointer]];\n"
        "\n"
        "_op_div: printf(\"\\nop_div\"); // div [1], 1 / div *1, 1\n"
        "    memory[opcode[instruction_pointer-1]] /= opcode[instruction_pointer+=2];\n"
        "    goto * dispatcher[opcode[++instruction_pointer]];\n"
        "\n"
        "// Сравнивать\n"
        "compare:\n"
        " printf(\"\\ncompare\"); // cmp [1], 1 / cmp *1, 1\n"
        " if (memory[opcode[instruction_pointer-1]] == opcode[instruction_pointer+=2]) {}\n"
        " goto * dispatcher[opcode[++instruction_pointer]];\n"
        "\n"
        "// Прыгни если не ноль\n"
        "jump_if_not_zero:\n"
        " printf(\"\\njump_if_not_zero\");\n"
        " return 0;"
        "\n"
        "// Вызов\n"
        "call:\n"
        " printf(\"\\ncall\");\n"
        " return 0;"
        "\n"
        "// Втолкнуть / положить на верхушку стека\n"
        "push:\n"
        " printf(\"\\npush\");\n"
        " return 0;"
        "\n"
        "// Вытолкнуть / снять с верхушки стека\n"
        "pop:\n"
        " printf(\"\\npop\");\n"
        " return 0;"
        "\n"
        "// Вернуться\n"
        "ret:\n"
        " printf(\"\\nret\");\n"
        " return 0;\n"
        "\n"
        "_op_invalid:\n"
        " printf(\"\\nop_invalid\");\n"
        " return 0;\n"
        "/*/ END_OF_BLOCK /*/\n"
        "    putchar('\\n');\n"
        "    return 0;\n"
        "}"
    );
    fclose(file);
    return 0;
}